# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
pyscript:
  allow_all_imports: true
  hass_is_global: true

logger:
  default: info
  logs:
    custom_components.pyscript: info

input_boolean:
  show_spinner:
    name: Show Spinner
    initial: false
    icon: mdi:dots-horizontal
  miner_running:
    name: Miner Running
    initial: false
    icon: mdi:dots-horizontal